#!/usr/bin/env python3
"""
generate_redline_docx.py

Generates a Word .docx with REAL tracked changes (w:ins/w:del) + REAL margin
comments (w:comment), plus visual fallback formatting (red strikethrough /
green underline) so it looks correct even where revisions are hidden.

Input: a JSON file with structure:
{
  "contract_title": "Freelancer MSA",
  "language": "hu" | "en",
  "score": { "current": 28, "after_redline": 82, "max": 100, "grade": "F" },
  "summary": {
    "high": 6, "medium": 4, "low": 2,
    "verdict": "Do not sign as-is."
  },
  "changes": [
    {
      "section": "3.1",
      "title": "IP overreach",
      "severity": "high" | "medium" | "low",
      "original": "All work product, ... whether or not related ...",
      "proposed": "Work product created specifically for ...",
      "why": "Túl tág IP-átruházás...",
      "legal_basis": "Szjt. 9. § (2), CA Labor Code 2870",
      "risk": "Elveszítheted a hobbi-projekted IP-jét.",
      "protects": "Csak a megrendelő részére végzett munka kerül át.",
      "tip": "Adj egy 'Prior IP' mellékletet a meglévő anyagokról."
    },
    ...
  ]
}

Output: REDLINED-<contract>.docx

Usage:
    python3 generate_redline_docx.py input.json output.docx
"""

import json
import sys
from datetime import datetime
from pathlib import Path

from docx import Document
from docx.enum.text import WD_COLOR_INDEX
from docx.oxml import OxmlElement
from docx.oxml.ns import nsmap, qn
from docx.shared import Pt, RGBColor, Inches
from lxml import etree


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

W_NS = "http://schemas.openxmlformats.org/wordprocessingml/2006/main"
nsmap_local = {"w": W_NS}

AUTHOR = "ContractMD AI"
DATE = datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")

SEVERITY_COLORS = {
    "high":   RGBColor(0xC0, 0x39, 0x2B),  # red
    "medium": RGBColor(0xD3, 0x8E, 0x00),  # orange
    "low":    RGBColor(0x2E, 0x86, 0x36),  # green
}
SEVERITY_LABELS = {
    "high":   "🔴 HIGH RISK",
    "medium": "🟡 MEDIUM",
    "low":    "🟢 LOW",
}
LANG_STRINGS = {
    "hu": {
        "cover_title": "Szerződés Redline Riport",
        "current_score": "Jelenlegi pontszám",
        "after_score": "Javítás utáni pontszám",
        "grade": "Osztályzat",
        "summary": "Összegzés",
        "verdict": "Verdikt",
        "changes_count": "Javasolt módosítások",
        "section": "Pont",
        "why": "Miért problémás",
        "legal": "Jogi alap",
        "risk": "⚠️ Mit kockáztat",
        "protects": "✓ Mit véd a módosítás",
        "tip": "💡 Tárgyalási tipp",
        "original": "Eredeti szöveg",
        "proposed": "Javasolt új szöveg",
        "overview": "Áttekintő táblázat",
        "footer": "Generálva: ContractMD AI · ",
        "instructions": (
            "Ez a dokumentum Word Tracked Changes (Változások követése) formátumban "
            "tartalmazza a javasolt módosításokat. Word-ben: Véleményezés → "
            "Változások elfogadása/elutasítása. A margón megjegyzések szerepelnek "
            "minden változtatás indoklásához."
        ),
    },
    "en": {
        "cover_title": "Contract Redline Report",
        "current_score": "Current score",
        "after_score": "Score after redline",
        "grade": "Grade",
        "summary": "Summary",
        "verdict": "Verdict",
        "changes_count": "Proposed changes",
        "section": "Section",
        "why": "Why this is a problem",
        "legal": "Legal basis",
        "risk": "⚠️ What you risk",
        "protects": "✓ What the change protects",
        "tip": "💡 Negotiation tip",
        "original": "Original text",
        "proposed": "Proposed new text",
        "overview": "Overview",
        "footer": "Generated by ContractMD AI · ",
        "instructions": (
            "This document uses Word's Track Changes format. In Word: "
            "Review → Accept/Reject changes. Comments in the margin explain "
            "each change."
        ),
    },
}


# ---------------------------------------------------------------------------
# Comment plumbing (python-docx has no native API for w:comment)
# ---------------------------------------------------------------------------

def _make_element(tag, **attrs):
    el = OxmlElement(tag)
    for k, v in attrs.items():
        el.set(qn(k), str(v))
    return el


COMMENTS_REL_TYPE = (
    "http://schemas.openxmlformats.org/officeDocument/2006/relationships/comments"
)
COMMENTS_CONTENT_TYPE = (
    "application/vnd.openxmlformats-officedocument.wordprocessingml.comments+xml"
)


def _ensure_comments_part(doc):
    """Adds /word/comments.xml part if missing. Returns (part, root element)."""
    from docx.opc.part import Part
    from docx.opc.packuri import PackURI

    main_part = doc.part
    package = main_part.package

    # Check existing relationships first
    for rel in main_part.rels.values():
        if rel.reltype == COMMENTS_REL_TYPE:
            comments_part = rel.target_part
            root = etree.fromstring(comments_part.blob)
            return comments_part, root

    partname = PackURI("/word/comments.xml")
    root = etree.Element(qn("w:comments"), nsmap={"w": W_NS})
    blob = etree.tostring(
        root, xml_declaration=True, encoding="UTF-8", standalone=True
    )
    comments_part = Part(partname, COMMENTS_CONTENT_TYPE, blob, package)
    main_part.relate_to(comments_part, COMMENTS_REL_TYPE)
    return comments_part, root


def _sync_comments_part(comments_part, root):
    blob = etree.tostring(
        root, xml_declaration=True, encoding="UTF-8", standalone=True
    )
    comments_part._blob = blob


_comment_counter = {"id": 0}


def add_comment_to_paragraph(doc, paragraph, text, author=AUTHOR):
    """Attaches a Word margin comment to the given paragraph."""
    comments_part, root = _ensure_comments_part(doc)
    cid = _comment_counter["id"]
    _comment_counter["id"] += 1

    # Build comment element
    comment = etree.SubElement(root, qn("w:comment"))
    comment.set(qn("w:id"), str(cid))
    comment.set(qn("w:author"), author)
    comment.set(qn("w:date"), DATE)
    comment.set(qn("w:initials"), "CMD")

    for line in text.split("\n"):
        p = etree.SubElement(comment, qn("w:p"))
        r = etree.SubElement(p, qn("w:r"))
        t = etree.SubElement(r, qn("w:t"))
        t.text = line
        t.set(qn("xml:space"), "preserve")

    _sync_comments_part(comments_part, root)

    # Insert range markers around the paragraph contents
    p_el = paragraph._p
    start = OxmlElement("w:commentRangeStart")
    start.set(qn("w:id"), str(cid))
    end = OxmlElement("w:commentRangeEnd")
    end.set(qn("w:id"), str(cid))
    ref_run = OxmlElement("w:r")
    ref = OxmlElement("w:commentReference")
    ref.set(qn("w:id"), str(cid))
    ref_run.append(ref)

    p_el.insert(0, start)
    p_el.append(end)
    p_el.append(ref_run)


# ---------------------------------------------------------------------------
# Tracked-change runs (w:ins / w:del)
# ---------------------------------------------------------------------------

_revision_counter = {"id": 1000}


def _next_rev_id():
    _revision_counter["id"] += 1
    return _revision_counter["id"]


def _run_with_props(text, *, strike=False, color=None, underline=False, bold=False, italic=False):
    """Build a w:r element with text + visual fallback formatting."""
    r = OxmlElement("w:r")
    rpr = OxmlElement("w:rPr")
    if bold:
        rpr.append(OxmlElement("w:b"))
    if italic:
        rpr.append(OxmlElement("w:i"))
    if strike:
        rpr.append(OxmlElement("w:strike"))
    if underline:
        u = OxmlElement("w:u")
        u.set(qn("w:val"), "single")
        rpr.append(u)
    if color:
        c = OxmlElement("w:color")
        c.set(qn("w:val"), color)
        rpr.append(c)
    r.append(rpr)
    t = OxmlElement("w:t")
    t.text = text
    t.set(qn("xml:space"), "preserve")
    r.append(t)
    return r


def add_tracked_deletion(paragraph, text):
    """Add a deletion as a real w:del + visual red strikethrough fallback."""
    p_el = paragraph._p
    del_el = OxmlElement("w:del")
    del_el.set(qn("w:id"), str(_next_rev_id()))
    del_el.set(qn("w:author"), AUTHOR)
    del_el.set(qn("w:date"), DATE)

    r = OxmlElement("w:r")
    rpr = OxmlElement("w:rPr")
    strike = OxmlElement("w:strike")
    rpr.append(strike)
    color = OxmlElement("w:color")
    color.set(qn("w:val"), "C0392B")
    rpr.append(color)
    r.append(rpr)
    # For deletions Word uses w:delText
    dt = OxmlElement("w:delText")
    dt.text = text
    dt.set(qn("xml:space"), "preserve")
    r.append(dt)
    del_el.append(r)
    p_el.append(del_el)


def add_tracked_insertion(paragraph, text):
    """Add an insertion as a real w:ins + visual green underline fallback."""
    p_el = paragraph._p
    ins_el = OxmlElement("w:ins")
    ins_el.set(qn("w:id"), str(_next_rev_id()))
    ins_el.set(qn("w:author"), AUTHOR)
    ins_el.set(qn("w:date"), DATE)

    r = _run_with_props(text, underline=True, color="2E8636")
    ins_el.append(r)
    p_el.append(ins_el)


# ---------------------------------------------------------------------------
# Cover & layout
# ---------------------------------------------------------------------------

def _shade_cell(cell, hex_color):
    tc_pr = cell._tc.get_or_add_tcPr()
    shd = OxmlElement("w:shd")
    shd.set(qn("w:val"), "clear")
    shd.set(qn("w:color"), "auto")
    shd.set(qn("w:fill"), hex_color)
    tc_pr.append(shd)


def build_cover(doc, data, L):
    """Cover page: title, score, grade, summary, verdict."""
    title = doc.add_paragraph()
    title_run = title.add_run(L["cover_title"])
    title_run.bold = True
    title_run.font.size = Pt(24)

    sub = doc.add_paragraph()
    sub_run = sub.add_run(data["contract_title"])
    sub_run.italic = True
    sub_run.font.size = Pt(14)
    sub_run.font.color.rgb = RGBColor(0x55, 0x55, 0x55)

    doc.add_paragraph()  # spacer

    # Score table
    score = data.get("score", {})
    table = doc.add_table(rows=2, cols=3)
    table.style = "Light Grid Accent 1"
    hdr = table.rows[0].cells
    hdr[0].text = L["current_score"]
    hdr[1].text = L["after_score"]
    hdr[2].text = L["grade"]
    for c in hdr:
        for p in c.paragraphs:
            for r in p.runs:
                r.bold = True

    body = table.rows[1].cells
    body[0].text = f"{score.get('current','?')}/{score.get('max',100)}"
    body[1].text = f"{score.get('after_redline','?')}/{score.get('max',100)}"
    body[2].text = str(score.get("grade", "?"))
    for p in body[0].paragraphs:
        for r in p.runs:
            r.bold = True
            r.font.size = Pt(20)
            r.font.color.rgb = RGBColor(0xC0, 0x39, 0x2B)
    for p in body[1].paragraphs:
        for r in p.runs:
            r.bold = True
            r.font.size = Pt(20)
            r.font.color.rgb = RGBColor(0x2E, 0x86, 0x36)

    doc.add_paragraph()

    # Severity summary
    summary = data.get("summary", {})
    sev_p = doc.add_paragraph()
    sev_p.add_run(f"🔴 {summary.get('high', 0)} High Risk    ").bold = True
    sev_p.add_run(f"🟡 {summary.get('medium', 0)} Medium    ").bold = True
    sev_p.add_run(f"🟢 {summary.get('low', 0)} Low").bold = True

    if summary.get("verdict"):
        v = doc.add_paragraph()
        v.add_run(f"{L['verdict']}: ").bold = True
        v_run = v.add_run(summary["verdict"])
        v_run.italic = True
        v_run.font.color.rgb = RGBColor(0xC0, 0x39, 0x2B)

    # Instructions
    doc.add_paragraph()
    inst = doc.add_paragraph()
    inst_run = inst.add_run(L["instructions"])
    inst_run.italic = True
    inst_run.font.size = Pt(9)
    inst_run.font.color.rgb = RGBColor(0x77, 0x77, 0x77)

    doc.add_page_break()


def build_change_block(doc, change, L, index):
    """One redlined change: heading + original (tracked deletion) + proposed (tracked insertion) + comment."""
    sev = change.get("severity", "medium")

    h = doc.add_paragraph()
    h.paragraph_format.space_before = Pt(18)
    badge = h.add_run(f"{SEVERITY_LABELS.get(sev,'')}  ")
    badge.bold = True
    badge.font.color.rgb = SEVERITY_COLORS.get(sev)
    badge.font.size = Pt(11)

    sec_run = h.add_run(f"{L['section']} {change.get('section','?')} — {change.get('title','')}")
    sec_run.bold = True
    sec_run.font.size = Pt(13)

    # Original (deleted)
    orig_p = doc.add_paragraph()
    orig_label = orig_p.add_run(f"{L['original']}: ")
    orig_label.bold = True
    orig_label.font.size = Pt(9)
    orig_label.font.color.rgb = RGBColor(0x77, 0x77, 0x77)
    add_tracked_deletion(orig_p, change.get("original", ""))

    # Proposed (inserted)
    new_p = doc.add_paragraph()
    new_label = new_p.add_run(f"{L['proposed']}: ")
    new_label.bold = True
    new_label.font.size = Pt(9)
    new_label.font.color.rgb = RGBColor(0x77, 0x77, 0x77)
    add_tracked_insertion(new_p, change.get("proposed", ""))

    # Build comment text
    comment_lines = []
    if change.get("why"):
        comment_lines.append(f"{L['why']}: {change['why']}")
    if change.get("legal_basis"):
        comment_lines.append(f"{L['legal']}: {change['legal_basis']}")
    if change.get("risk"):
        comment_lines.append(f"{L['risk']}: {change['risk']}")
    if change.get("protects"):
        comment_lines.append(f"{L['protects']}: {change['protects']}")
    if change.get("tip"):
        comment_lines.append(f"{L['tip']}: {change['tip']}")

    if comment_lines:
        # Anchor comment on the new_p paragraph (the proposed text)
        add_comment_to_paragraph(doc, new_p, "\n\n".join(comment_lines))

    # Visual inline explanation card (so it's readable even with revisions hidden)
    card = doc.add_table(rows=len(comment_lines), cols=1)
    card.autofit = True
    for i, line in enumerate(comment_lines):
        cell = card.rows[i].cells[0]
        _shade_cell(cell, "FFF8DC")  # soft yellow
        cell.text = line
        for p in cell.paragraphs:
            for r in p.runs:
                r.font.size = Pt(9)


def build_overview_table(doc, data, L):
    doc.add_page_break()
    h = doc.add_paragraph()
    h_run = h.add_run(L["overview"])
    h_run.bold = True
    h_run.font.size = Pt(16)

    changes = data.get("changes", [])
    table = doc.add_table(rows=len(changes) + 1, cols=4)
    table.style = "Light List Accent 1"

    hdr = table.rows[0].cells
    hdr[0].text = L["section"]
    hdr[1].text = "Severity"
    hdr[2].text = "Title"
    hdr[3].text = L["risk"]
    for c in hdr:
        for p in c.paragraphs:
            for r in p.runs:
                r.bold = True

    for i, ch in enumerate(changes, start=1):
        row = table.rows[i].cells
        row[0].text = str(ch.get("section", ""))
        sev = ch.get("severity", "medium")
        row[1].text = SEVERITY_LABELS.get(sev, "")
        row[2].text = str(ch.get("title", ""))
        row[3].text = str(ch.get("risk", "") or "")
        for c in row:
            for p in c.paragraphs:
                for r in p.runs:
                    r.font.size = Pt(9)


def add_footer(doc, L):
    section = doc.sections[0]
    footer = section.footer
    p = footer.paragraphs[0]
    p.text = f"{L['footer']}{datetime.utcnow().strftime('%Y-%m-%d')}"
    for r in p.runs:
        r.font.size = Pt(8)
        r.font.color.rgb = RGBColor(0x99, 0x99, 0x99)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def generate_redline(input_json_path, output_docx_path):
    with open(input_json_path, "r", encoding="utf-8") as fh:
        data = json.load(fh)

    lang = data.get("language", "en")
    L = LANG_STRINGS.get(lang, LANG_STRINGS["en"])

    doc = Document()

    # Wider margins so margin comments have room
    for section in doc.sections:
        section.left_margin = Inches(0.8)
        section.right_margin = Inches(2.4)
        section.top_margin = Inches(0.8)
        section.bottom_margin = Inches(0.8)

    build_cover(doc, data, L)

    for i, change in enumerate(data.get("changes", [])):
        build_change_block(doc, change, L, i)

    build_overview_table(doc, data, L)
    add_footer(doc, L)

    doc.save(output_docx_path)
    print(f"✓ Generated: {output_docx_path}")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python3 generate_redline_docx.py <input.json> <output.docx>")
        sys.exit(1)
    generate_redline(sys.argv[1], sys.argv[2])
